spring.profiles.active: ${env:dev}

### logging
logging:
  file: pm-brenda.log
  level.com.taco.bbss: INFO

### Database
spring:
  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    database: POSTGRESQL
    show-sql: false
  messages.basename: i18n/messages

### Email
spring.mail:
  host: smtp.gmail.com
  port: 587
  properties.mail.transport.protocol: smtp
  properties.mail.smtp.starttls.enable: true
  properties.mail.smtp.auth: true
  properties.mail.debug: true
  username: drabbss@gmail.com
  password: bbss&0404&2612
